language: rust
before_script:
    - rustup component add clippy-preview
    - rustup component add rustfmt-preview
script:
    - cargo fmt --all -- --check
    - cargo clippy -- --deny warnings
    - cargo check
