version: '3.3'
services:
  bot:
    image: quasiyoke/comrade-colonel-bot
    secrets:
      - telegram_bot_token
    environment:
      RUST_BACKTRACE: '1'
      RUST_LOG: comrade_colonel_bot=info
      STORAGE_PATH: /var/lib/comrade-colonel-bot/db.sqlite3
    restart: always
    volumes:
      - /var/lib/comrade-colonel-bot/:/var/lib/comrade-colonel-bot/
    labels:
      com.centurylinklabs.watchtower.enable: true
  updater:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable
secrets:
  telegram_bot_token:
    file: ./telegram-bot-token
