apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: comrade-colonel-bot
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: comrade-colonel-bot
        spec:
            containers:
            - name: comrade-colonel-bot
                image: loyd/comrade-colonel-bot:latest
                env:
                - name: TELEGRAM_BOT_TOKEN
                    valueFrom:
                        secretKeyRef:
                            name: comrade-colonel-bot
                            key: telegram-bot-token
